# pubspec.yaml
name: paket_3_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  dio: ^5.9.0
  riverpod: ^3.1.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.12.0
  intl: ^0.20.2
  image_picker: ^1.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^1.1.1
  path: ^1.9.1
  url_launcher: ^6.3.2
  go_router: ^17.0.1
  permission_handler: ^12.0.1
  file_picker: ^10.3.8
  flutter_riverpod: ^3.1.0
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  flutter_animate: ^4.5.2
  uuid: ^4.5.2
  mime: ^2.0.0
  image_picker_for_web: ^3.1.1
  universal_html: ^2.3.0
  path_provider: ^2.1.5
  open_filex: ^4.6.0
  csv: ^6.0.0
  excel: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpg"
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/appicon.jpg
    - assets/images/icon.jpg